import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { QueryProviders } from "@/components/query-provider";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jira Clone",
  description: "Generated by create next app",
  icons: "/logo.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "antialiased min-h-screen"
        )}>
        <QueryProviders>
          {" "}
          <Toaster />
          {children}
        </QueryProviders>
      </body>
    </html>
  );
}
